name: EnderTownyDynampPlugin
version: '${project.version}'
main: com.theendercore.endertownydynamp.EnderTownyDynamp
api-version: 1.18
authors: [ Ender ]
description: pp
website: emlo40.com
commands:
  penis:
    description:
      tell you penis.
    usage: /<command>
    aliases: